apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default-applicationset
  namespace: default
spec:
  generators:
    - list:
        elements:
          - name: cert-manager
            namespace: platform-security
            version: 1.14.4
            train: external
          - name: local-path-provisioner
            namespace: platform-storage
            version: 0.0.26
            train: external
          - name: cloudnative-pg
            namespace: platform-data
            version: 0.20.1
            train: external
          - name: kyverno
            namespace: platform-security
            version: 3.1.4
            train: external
          - name: traefik
            namespace: platform-ingress
            version: 26.1.0
            train: external
          - name: kube-prometheus-stack
            namespace: platform-observability
            version: 57.0.2
            train: external
          - name: redis-operator
            namespace: platform-data
            version: 3.3.0
            train: external
          - name: loki
            namespace: platform-observability
            version: 5.43.6
            train: external
          # - name: velero
          #   namespace: platform-storage
          #   version: 6.0.0
          #   train: external
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: projectwhitebox
      source:
        repoURL: https://github.com/jamie-stinson/server-charts
        path: 'charts/{{train}}/{{name}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - CreateNamespace=false
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=false
          - ApplyOutOfSyncOnly=false
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m