apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: projectwhitebox
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project Whitebox
  sourceRepos:
  - '*'