apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: cert-manager
spec:
  project: projectwhitebox
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.4
    path: cert-manager

    chart: cert-manager
    helm:
      releaseName: cert-manager
      skipCrds: false
      valuesObject:
        installCRDs: true

  destination:
    server: https://kubernetes.default.svc
    namespace: platform-security

  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=false

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m